import type { Metadata } from "next";
import "../globals.css";
import { Roboto } from "next/font/google";
import Link from "next/link";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import NavBar from "./NavBar";

const roboto = Roboto({
  weight: "400", // You can omit this if you don't need a specific weight
  subsets: ["latin"], // Specify the character subsets
});

export const metadata: Metadata = {
  title: "Threads Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="dracula">
        <body className={roboto.className}>
          <NavBar />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
