import type { Metadata } from "next";
import "../globals.css";

import { Bebas_Neue } from "next/font/google";

const bebas = Bebas_Neue({
  weight: "400", // You can omit this if you don't need a specific weight
  subsets: ["latin"], // Specify the character subsets
});

export const metadata: Metadata = {
  title: "Threads Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bebas.className}>{children}</body>
    </html>
  );
}
