import type { Metadata } from "next";
import "../globals.css";
import { Roboto } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Threads Clone",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
    // </ClerkProvider>
  );
}
